name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 0 点运行一次，可根据需要调整频率
  workflow_dispatch:    # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git configuration
        run: |
          git config user.name "sodardyjiber"
          git config user.email "sodardyjiber@outlook.com"

      - name: Remove existing upstream if any
        run: git remote remove upstream || true

      - name: Add upstream repository
        run: git remote add upstream https://github.com/bia-pain-bache/BPB-Worker-Panel.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes to fork
        run: git push origin main
